# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/npm.gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt-get update -qy
    - apt-get install --no-install-recommends -y npm
    - npm --version
    - cd api/ 
    - pwd
    - rm -rf node_modules
    - sudo apt-get install build-essential
    - npm i
  script:
    - pwd
    - npm run build
