image: node:latest

stages:
  - build
  # - test

api build:
  stage: build
  # before_script:
  #   - apt-get update -qy
  #   - apt-get install --no-install-recommends -y npm
  #   - npm --version
  #   - cd ui/ 
  #   - pwd
  #   - npm i
  script:
    - cd api/
    - pwd

    # - |
    #   if  [ ! -f .npmrc ]; then echo .npmrc missing. Creating one now.
    #     export NPM_PROJECT_URL=$(echo "$CI_PROJECT_URL" | sed "s/${CI_PROJECT_PATH//\//\\/}/api\/v4/g")
    #     export NPM_REGISTRY_PATHS=$(echo "$CI_PROJECT_URL" | sed "s/${CI_PROJECT_PATH//\//\\/}/api\/v4/g")
    #     export NPMRC_URL=$(echo "$NPM_REGISTRY_PATHS" | sed 's/[^:]*[:]//')
    #     export NPMRC_INSTALL_URL=$(echo "$NPMRC_URL/packages/npm/:_authToken=$GITLAB_TOKEN")
    #     # export NPMRC_PUBLISH_URL=$(echo "$NPMRC_URL/projects/$CI_PROJECT_ID/packages/npm/:_authToken=$GITLAB_TOKEN")
    #     export NPM_SCOPE=$(echo "$CI_PROJECT_PATH" | sed 's/[/].*$//')
    #     echo "@$NPM_SCOPE:registry=$NPM_REGISTRY_PATHS/packages/npm/" >> .npmrc
    #     echo "$NPMRC_INSTALL_URL" >> .npmrc
    #     # echo "$NPMRC_PUBLISH_URL" >> .npmrc
    #   fi

    # - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - echo "//$CI_PROJECT_URL/api/v4/packages/npm/:_authToken=$GITLAB_TOKEN" >>.npmrc
    - echo "@CI_PROJECT_PATH:registry=https://git.cardiff.ac.uk/api/v4/packages/npm/" >> .npmrc
    # - npm publish #--registry=--registry=https://gitlab.com/api/v4/packages/npm/
    # - echo "This is a build job for ui"
    # - npm run build
    # - echo "@c2061455:registry=https://git.cardiff.ac.uk/api/v4/packages/npm/ //git.cardiff.ac.uk/api/v4/packages/npm/:_authToken=$GITLAB_TOKEN" > .npmrc
    # - npm config set registry https://git.cardiff.ac.uk/api/v4/packages/npm/
    - npm i @c2061455/api
  only:
    - cicd
  artifacts:
    paths:
      - .npmrc

# ui unit test:
#   stage: test
#   # before_script:
#   #   - apt-get update -qy
#   #   - apt-get install --no-install-recommends -y npm
#   #   - npm --version
#   #   - cd ui/ 
#   #   - pwd
#   #   - npm i
#   script:
#     - cd ui/ 
#     - pwd
#     - echo "This is a test job for ui"
    # - npm test