stages:
  - build
  - test

ui build:
  stage: build
  # before_script:
  #   - apt-get update -qy
  #   - apt-get install --no-install-recommends -y npm
  #   - npm --version
  #   - cd ui/ 
  #   - pwd
  #   - npm i
  script:
    - cd ui/
    - pwd
    - echo "This is a build job for ui"
    # - npm run build

ui unit test:
  stage: test
  # before_script:
  #   - apt-get update -qy
  #   - apt-get install --no-install-recommends -y npm
  #   - npm --version
  #   - cd ui/ 
  #   - pwd
  #   - npm i
  script:
    - cd ui/ 
    - pwd
    - echo "This is a test job for ui"
    # - npm test